### ISSUE TITLE
top函数是哪个

### ISSUE THREAD

**Issue by zhanghb1915** [a2824256/HLS-LeNet#1]
用不同的top函数  csim的结果不一样  lenet为top是res7
在Cosimulation时有错误是我的环境有问题吗
ERROR: [VRFC 10-3032] 'floating_point_v7_1_7.floating_point_v7_1_7_viv' failed to restore  11:solution1  2019年5月14日 上午1:15:25
ERROR: [VRFC 10-213] Registering Dependencies Error: The library 'xbip_pipe_v3_0_5' could not be found during restore   11:solution1  2019年5月14日 上午1:15:24
ERROR: [VRFC 10-3032] 'xbip_pipe_v3_0_5.xbip_pipe_v3_0_5_viv_comp' failed to restore  11:solution1  2019年5月14日 上午1:15:24

**Comment by yfu5** [comment]
不同的top函数？

**Comment by a2824256** [comment]
top函数是lenet。目前这个网络还在进一步的完善中。
